### ISSUE TITLE
No autocomplete suggestion coming

### ISSUE THREAD

**Issue by PallavRastogi** [codota/jupyter-tabnine#68]
All the installation commands were successful, not a single error was shown during installation.
But the tabnine extension is just not working, whenever I type something an error is dumped in the console tab.

[
![Tabnine Error](https://user-images.githubusercontent.com/69533542/115369053-558fc400-a1e5-11eb-9e1e-f3d8fa8f928f.JPG)
](url)

**Comment by yachtsman** [comment]
I have the same issue. Moreover, it happens accidentally, after the reloading jupyter, Tabnine is running for a while and then stops work again.

**Comment by plehman2000** [comment]
Same issue, same error as PallavRastogi

**Comment by timsolov** [comment]
Same issue

**Comment by dimacodota** [comment]
can you please attach the output of the `jupyter notebook` command in the `Command Prompt`?

**Comment by hustxujinkang** [comment]
> can you please attach the output of the `jupyter notebook` command in the `Command Prompt`?
[E 18:12:08.320 NotebookApp] Uncaught exception GET /tabnine?data=%7B%22version%22%3A%221.0.7%22%2C%22request%22%3A%7B%22Autocomplete%22%3A%7B%22filename%22%3A%22dlnlp%2Fdynamic_graph_e3.py%22%2C%22before%22%3A%22import%20tensorflow%20as%20tf%5Cnimport%20numpy%20as%20np%5Cnimport%20matplotlib.pyplot%20as%20plt%5Cntf.compat.v1.disable_v2_behavior()%5Cn%23%EF%BC%881%EF%BC%89%E7%94%9F%E6%88%90%E6%A8%A1%E6%8B%9F%E6%95%B0%E6%8D%AE%5Cntrain_X%20%3D%20np.linspace(-1%2C%201%2C%20100)%5Cntrain_Y%20%3D%202%20*%20train_X%20%2B%20np.random.randn(*train_X.shape)%20*%200.3%20%23%20y%3D2x%EF%BC%8C%E4%BD%86%E6%98%AF%E5%8A%A0%E5%85%A5%E4%BA%86%E5%99%AA%E5%A3%B0%5Cn%23%E5%9B%BE%E5%BD%A2%E6%98%BE%E7%A4%BA%5Cnplt.plot(train_X%2C%20train_Y%2C%20%27ro%27%2C%20label%3D%27Original%20data%27)%5Cnplt.legend()%5Cnplt.show()%5Cntf.compat.v1.reset_default_graph()%5Cndef%20my_py_func(X%2C%20W%2C%20b)%3A%5Cn%20%20%20%20z%20%3D%20tf.multiply(X%2C%20W)%20%2B%20b%5Cn%20%20%20%20print(z)%5Cn%20%20%20%20return%20z%5CnX%20%3D%20tf.compat.v1.placeholder(%5C%22float%5C%22)%5CnY%20%3D%20tf.compat.v1.placeholder(%5C%22float%5C%22)%5CnW%22%2C%22after%22%3A%22%22%2C%22region_includes_beginning%22%3Atrue%2C%22region_includes_end%22%3Atrue%2C%22max_num_results%22%3A10%7D%7D%7D (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/tabnine?data=%7B%22version%22%3A%221.0.7%22%2C%22request%22%3A%7B%22Autocomplete%22%3A%7B%22filename%22%3A%22dlnlp%2Fdynamic_graph_e3.py%22%2C%22before%22%3A%22import%20tensorflow%20as%20tf%5Cnimport%20numpy%20as%20np%5Cnimport%20matplotlib.pyplot%20as%20plt%5Cntf.compat.v1.disable_v2_behavior()%5Cn%23%EF%BC%881%EF%BC%89%E7%94%9F%E6%88%90%E6%A8%A1%E6%8B%9F%E6%95%B0%E6%8D%AE%5Cntrain_X%20%3D%20np.linspace(-1%2C%201%2C%20100)%5Cntrain_Y%20%3D%202%20*%20train_X%20%2B%20np.random.randn(*train_X.shape)%20*%200.3%20%23%20y%3D2x%EF%BC%8C%E4%BD%86%E6%98%AF%E5%8A%A0%E5%85%A5%E4%BA%86%E5%99%AA%E5%A3%B0%5Cn%23%E5%9B%BE%E5%BD%A2%E6%98%BE%E7%A4%BA%5Cnplt.plot(train_X%2C%20train_Y%2C%20%27ro%27%2C%20label%3D%27Original%20data%27)%5Cnplt.legend()%5Cnplt.show()%5Cntf.compat.v1.reset_default_graph()%5Cndef%20my_py_func(X%2C%20W%2C%20b)%3A%5Cn%20%20%20%20z%20%3D%20tf.multiply(X%2C%20W)%20%2B%20b%5Cn%20%20%20%20print(z)%5Cn%20%20%20%20return%20z%5CnX%20%3D%20tf.compat.v1.placeholder(%5C%22float%5C%22)%5CnY%20%3D%20tf.compat.v1.placeholder(%5C%22float%5C%22)%5CnW%22%2C%22after%22%3A%22%22%2C%22region_includes_beginning%22%3Atrue%2C%22region_includes_end%22%3Atrue%2C%22max_num_results%22%3A10%7D%7D%7D', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\users\hustx\miniconda3\envs\pygpu\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "c:\users\hustx\miniconda3\envs\pygpu\lib\site-packages\jupyter_tabnine\handler.py", line 13, in get
        response = self.tabnine.request(request_data)
      File "c:\users\hustx\miniconda3\envs\pygpu\lib\site-packages\jupyter_tabnine\tabnine.py", line 104, in request
        proc.stdin.flush()
    OSError: [Errno 22] Invalid argument
[E 18:12:08.324 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"92\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"92\"",
      "Accept": "*/*",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/notebooks/dlnlp/dynamic_graph_e3.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5",
      "Cookie": "_ga=GA1.1.638351819.1615285612; _xsrf=2|64dee960|2650b915acc97f55602e5e2194eda131|1626484749; username-localhost-8889=\"2|1:0|10:1627431870|23:username-localhost-8889|44:Njk5NGZkYmRhODJkNDc1MGFkZmNhNDcxYTk0ZjUwYjU=|150307e9d0bcba6433105ec2000a7353d3698f3422b3d5cd66794ae1b6b07fc7\"; _gid=GA1.1.1082212565.1627914988; username-localhost-8888=\"2|1:0|10:1628417387|23:username-localhost-8888|44:MTBmMzIwMTJiMGI1NDJjZWJmMDliMTAzMDYwNTAwY2E=|26751b91427640d2e419574d4f4210ea65058bb6d0a11bfb475e75a1e2ac2d1a\"; _gat=1"
    }
