### ISSUE TITLE
Can't uninstall tabnine

### ISSUE THREAD

**Issue by I-Avery** [codota/jupyter-tabnine#81]
Hello, I'm not super familiar with github and so I hope I'm putting this in the right place.

I followed the instructions for installing tabnine in jupyter lab and it worked great. Now I'd like to uninstall it, but when entering the following commands into my terminal:
`jupyter nbextension uninstall --py jupyter_tabnine`
`pip3 uninstall jupyter-tabnine`

I get the following output:

`Traceback (most recent call last):
  File "/Users/glados/opt/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 980, in start
    super().start()
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 253, in start
    self.subapp.start()
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 888, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 864, in toggle_nbextension_python
    logger=self.log)
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 498, in disable_nbextension_python
    logger=logger)
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 372, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "/Users/glados/opt/anaconda3/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])`

`ModuleNotFoundError: No module named 'jupyter_tabnine'`

I'm assuming that last line "ModuleNotFoundError: No module named 'jupyter_tabnine' " is the core issue.

For reference I use jupyterlab which I always launch from the anaconda gui 

When I open jupyterlab, tabnine is still there and still working so clearly the module is _somewhere_

Any suggestions for how to successfully uninstall tabnine? 

gz#12369

**Comment by maya-tabnine** [comment]
Hi @I-Avery you say you use Jupyer Lab, right?
Will you try run `pip3 uninstall jupyterlab-tabnine` ?

**Comment by I-Avery** [comment]
Great suggestion! That worked worked perfectly thanks. I'll close the issue.
